---
slug: foobaz
filename: foobaz
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 1b442c05-dfb4-4fff-8fc6-0360c9328a8b
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
